// Comprehensive Fabric Data Architecture for Karacabey Tekstil Showroom
// Designed to handle 400+ products with full technical specifications

export type FabricCategory =
  | 'velvet'
  | 'satin'
  | 'linen'
  | 'jacquard'
  | 'silk'
  | 'chenille'
  | 'organza'
  | 'taffeta'
  | 'brocade'
  | 'damask'
  | 'suede'
  | 'blackout'
  | 'sheer'

export type UsageArea =
  | 'curtains'
  | 'upholstery'
  | 'bedding'
  | 'tablecloth'
  | 'cushions'
  | 'wall-panels'
  | 'event-decor'
  | 'headboards'
  | 'throws'

export type WashingInstruction =
  | 'machine-wash-30'
  | 'machine-wash-40'
  | 'machine-wash-60'
  | 'hand-wash'
  | 'dry-clean-only'
  | 'do-not-bleach'
  | 'do-not-tumble-dry'
  | 'tumble-dry-low'
  | 'iron-low'
  | 'iron-medium'
  | 'iron-high'
  | 'professional-care'

export interface FabricComposition {
  cotton?: number
  polyester?: number
  viscose?: number
  silk?: number
  linen?: number
  wool?: number
  acrylic?: number
  nylon?: number
  metallic?: number
}

export interface FabricProduct {
  id: string
  name: string
  category: FabricCategory
  sku: string
  width: number // in cm
  weight: number // in g/m² (GSM)
  composition: FabricComposition
  usageAreas: UsageArea[]
  washingInstructions: WashingInstruction[]
  colors: string[]
  pattern?: string
  finish?: string
  martindale?: number // abrasion resistance
  lightFastness?: number // 1-8 scale
  fireRetardant?: boolean
  images: {
    primary: string
    detail?: string
    styled?: string[]
  }
  minOrder: number // in meters
  priceCategory: 1 | 2 | 3 | 4 | 5 // $ to $$$$$
  featured?: boolean
  new?: boolean
  bestseller?: boolean
}

// Washing instruction labels for display
export const washingInstructionLabels: Record<WashingInstruction, { en: string; tr: string; ru: string }> = {
  'machine-wash-30': { en: 'Machine wash 30°C', tr: 'Makinede yıkama 30°C', ru: 'Машинная стирка 30°C' },
  'machine-wash-40': { en: 'Machine wash 40°C', tr: 'Makinede yıkama 40°C', ru: 'Машинная стирка 40°C' },
  'machine-wash-60': { en: 'Machine wash 60°C', tr: 'Makinede yıkama 60°C', ru: 'Машинная стирка 60°C' },
  'hand-wash': { en: 'Hand wash only', tr: 'Sadece elde yıkama', ru: 'Только ручная стирка' },
  'dry-clean-only': { en: 'Dry clean only', tr: 'Sadece kuru temizleme', ru: 'Только химчистка' },
  'do-not-bleach': { en: 'Do not bleach', tr: 'Ağartmayın', ru: 'Не отбеливать' },
  'do-not-tumble-dry': { en: 'Do not tumble dry', tr: 'Kurutma makinesinde kurutmayın', ru: 'Не сушить в машине' },
  'tumble-dry-low': { en: 'Tumble dry low', tr: 'Düşük ısıda kurutma', ru: 'Сушка при низкой температуре' },
  'iron-low': { en: 'Iron on low heat', tr: 'Düşük ısıda ütüleme', ru: 'Гладить при низкой температуре' },
  'iron-medium': { en: 'Iron on medium heat', tr: 'Orta ısıda ütüleme', ru: 'Гладить при средней температуре' },
  'iron-high': { en: 'Iron on high heat', tr: 'Yüksek ısıda ütüleme', ru: 'Гладить при высокой температуре' },
  'professional-care': { en: 'Professional care recommended', tr: 'Profesyonel bakım önerilir', ru: 'Рекомендуется профессиональный уход' },
}

// Category labels for display
export const categoryLabels: Record<FabricCategory, { en: string; tr: string; ru: string }> = {
  velvet: { en: 'Velvet', tr: 'Kadife', ru: 'Бархат' },
  satin: { en: 'Satin', tr: 'Saten', ru: 'Атлас' },
  linen: { en: 'Linen', tr: 'Keten', ru: 'Лён' },
  jacquard: { en: 'Jacquard', tr: 'Jakar', ru: 'Жаккард' },
  silk: { en: 'Silk Blend', tr: 'İpek Karışım', ru: 'Шёлковая смесь' },
  chenille: { en: 'Chenille', tr: 'Şönil', ru: 'Шенилл' },
  organza: { en: 'Organza', tr: 'Organze', ru: 'Органза' },
  taffeta: { en: 'Taffeta', tr: 'Tafta', ru: 'Тафта' },
  brocade: { en: 'Brocade', tr: 'Brokar', ru: 'Парча' },
  damask: { en: 'Damask', tr: 'Şam Kumaşı', ru: 'Дамаск' },
  suede: { en: 'Suede', tr: 'Süet', ru: 'Замша' },
  blackout: { en: 'Blackout', tr: 'Karartma', ru: 'Блэкаут' },
  sheer: { en: 'Sheer', tr: 'Tül', ru: 'Тюль' },
}

// Usage area labels
export const usageAreaLabels: Record<UsageArea, { en: string; tr: string; ru: string }> = {
  curtains: { en: 'Curtains', tr: 'Perdeler', ru: 'Шторы' },
  upholstery: { en: 'Upholstery', tr: 'Döşeme', ru: 'Обивка' },
  bedding: { en: 'Bedding', tr: 'Yatak Takımı', ru: 'Постельное бельё' },
  tablecloth: { en: 'Tablecloths', tr: 'Masa Örtüsü', ru: 'Скатерти' },
  cushions: { en: 'Cushions', tr: 'Yastıklar', ru: 'Подушки' },
  'wall-panels': { en: 'Wall Panels', tr: 'Duvar Panelleri', ru: 'Стеновые панели' },
  'event-decor': { en: 'Event Decor', tr: 'Etkinlik Dekorasyonu', ru: 'Декор мероприятий' },
  headboards: { en: 'Headboards', tr: 'Yatak Başlıkları', ru: 'Изголовья' },
  throws: { en: 'Throws', tr: 'Örtüler', ru: 'Пледы' },
}

// Comprehensive Fabric Database
// This simulates 400+ products across all categories
export const FABRIC_DATA: FabricProduct[] = [
  // ============ VELVET COLLECTION ============
  {
    id: 'vel-001',
    name: 'Royal Emerald Velvet',
    category: 'velvet',
    sku: 'VEL-EMR-280',
    width: 280,
    weight: 350,
    composition: { polyester: 100 },
    usageAreas: ['curtains', 'upholstery', 'cushions', 'headboards'],
    washingInstructions: ['dry-clean-only', 'do-not-bleach', 'iron-low'],
    colors: ['Emerald', 'Forest', 'Sage'],
    pattern: 'Solid',
    finish: 'Crushed',
    martindale: 40000,
    lightFastness: 5,
    fireRetardant: true,
    images: { primary: '/images/fabric-velvet.jpg' },
    minOrder: 50,
    priceCategory: 4,
    featured: true,
    bestseller: true,
  },
  {
    id: 'vel-002',
    name: 'Burgundy Imperial Velvet',
    category: 'velvet',
    sku: 'VEL-BRG-280',
    width: 280,
    weight: 380,
    composition: { polyester: 85, viscose: 15 },
    usageAreas: ['curtains', 'upholstery', 'headboards'],
    washingInstructions: ['dry-clean-only', 'do-not-bleach', 'professional-care'],
    colors: ['Burgundy', 'Wine', 'Plum'],
    pattern: 'Solid',
    finish: 'Plain',
    martindale: 45000,
    lightFastness: 6,
    fireRetardant: true,
    images: { primary: '/images/fabric-velvet.jpg' },
    minOrder: 50,
    priceCategory: 4,
    new: true,
  },
  {
    id: 'vel-003',
    name: 'Navy Midnight Velvet',
    category: 'velvet',
    sku: 'VEL-NVY-280',
    width: 280,
    weight: 360,
    composition: { polyester: 100 },
    usageAreas: ['curtains', 'upholstery', 'cushions'],
    washingInstructions: ['dry-clean-only', 'do-not-bleach', 'iron-low'],
    colors: ['Navy', 'Midnight', 'Cobalt'],
    pattern: 'Solid',
    finish: 'Plain',
    martindale: 42000,
    lightFastness: 5,
    images: { primary: '/images/fabric-velvet.jpg' },
    minOrder: 40,
    priceCategory: 4,
  },
  {
    id: 'vel-004',
    name: 'Gold Luxe Velvet',
    category: 'velvet',
    sku: 'VEL-GLD-280',
    width: 280,
    weight: 340,
    composition: { polyester: 90, metallic: 10 },
    usageAreas: ['curtains', 'cushions', 'event-decor'],
    washingInstructions: ['dry-clean-only', 'do-not-bleach', 'professional-care'],
    colors: ['Antique Gold', 'Champagne', 'Bronze'],
    pattern: 'Solid',
    finish: 'Shimmer',
    martindale: 35000,
    lightFastness: 4,
    images: { primary: '/images/fabric-velvet.jpg' },
    minOrder: 30,
    priceCategory: 5,
    featured: true,
  },
  {
    id: 'vel-005',
    name: 'Ivory Pearl Velvet',
    category: 'velvet',
    sku: 'VEL-IVY-280',
    width: 280,
    weight: 330,
    composition: { polyester: 100 },
    usageAreas: ['curtains', 'bedding', 'cushions'],
    washingInstructions: ['dry-clean-only', 'do-not-bleach', 'iron-low'],
    colors: ['Ivory', 'Cream', 'Pearl'],
    pattern: 'Solid',
    finish: 'Plain',
    martindale: 38000,
    lightFastness: 5,
    images: { primary: '/images/fabric-velvet.jpg' },
    minOrder: 40,
    priceCategory: 3,
  },
  {
    id: 'vel-006',
    name: 'Charcoal Smoke Velvet',
    category: 'velvet',
    sku: 'VEL-CHR-280',
    width: 280,
    weight: 370,
    composition: { polyester: 100 },
    usageAreas: ['upholstery', 'headboards', 'wall-panels'],
    washingInstructions: ['dry-clean-only', 'do-not-bleach', 'iron-low'],
    colors: ['Charcoal', 'Slate', 'Graphite'],
    pattern: 'Solid',
    finish: 'Plain',
    martindale: 50000,
    lightFastness: 6,
    fireRetardant: true,
    images: { primary: '/images/fabric-velvet.jpg' },
    minOrder: 50,
    priceCategory: 4,
    bestseller: true,
  },

  // ============ SATIN COLLECTION ============
  {
    id: 'sat-001',
    name: 'Champagne Dream Satin',
    category: 'satin',
    sku: 'SAT-CHP-300',
    width: 300,
    weight: 180,
    composition: { polyester: 85, viscose: 15 },
    usageAreas: ['bedding', 'curtains', 'event-decor', 'tablecloth'],
    washingInstructions: ['machine-wash-30', 'do-not-tumble-dry', 'iron-medium'],
    colors: ['Champagne', 'Gold', 'Blush'],
    pattern: 'Solid',
    finish: 'High Sheen',
    lightFastness: 5,
    images: { primary: '/images/fabric-satin.jpg' },
    minOrder: 30,
    priceCategory: 3,
    featured: true,
    bestseller: true,
  },
  {
    id: 'sat-002',
    name: 'Silver Moon Satin',
    category: 'satin',
    sku: 'SAT-SLV-300',
    width: 300,
    weight: 175,
    composition: { polyester: 100 },
    usageAreas: ['bedding', 'curtains', 'event-decor'],
    washingInstructions: ['machine-wash-30', 'do-not-tumble-dry', 'iron-medium'],
    colors: ['Silver', 'Platinum', 'Ice Blue'],
    pattern: 'Solid',
    finish: 'High Sheen',
    lightFastness: 5,
    images: { primary: '/images/fabric-satin.jpg' },
    minOrder: 30,
    priceCategory: 3,
  },
  {
    id: 'sat-003',
    name: 'Blush Rose Satin',
    category: 'satin',
    sku: 'SAT-BLS-300',
    width: 300,
    weight: 180,
    composition: { polyester: 85, viscose: 15 },
    usageAreas: ['bedding', 'event-decor', 'cushions'],
    washingInstructions: ['machine-wash-30', 'do-not-tumble-dry', 'iron-medium'],
    colors: ['Blush', 'Dusty Rose', 'Mauve'],
    pattern: 'Solid',
    finish: 'High Sheen',
    lightFastness: 4,
    images: { primary: '/images/fabric-satin.jpg' },
    minOrder: 25,
    priceCategory: 3,
    new: true,
  },
  {
    id: 'sat-004',
    name: 'Pearl White Satin',
    category: 'satin',
    sku: 'SAT-PRL-300',
    width: 300,
    weight: 170,
    composition: { polyester: 100 },
    usageAreas: ['bedding', 'event-decor', 'tablecloth'],
    washingInstructions: ['machine-wash-30', 'do-not-bleach', 'iron-medium'],
    colors: ['Pearl', 'Ivory', 'Snow White'],
    pattern: 'Solid',
    finish: 'Matte Sheen',
    lightFastness: 5,
    images: { primary: '/images/fabric-satin.jpg' },
    minOrder: 25,
    priceCategory: 2,
  },
  {
    id: 'sat-005',
    name: 'Midnight Black Satin',
    category: 'satin',
    sku: 'SAT-BLK-300',
    width: 300,
    weight: 185,
    composition: { polyester: 100 },
    usageAreas: ['bedding', 'curtains', 'event-decor'],
    washingInstructions: ['machine-wash-30', 'do-not-tumble-dry', 'iron-medium'],
    colors: ['Black', 'Onyx', 'Jet'],
    pattern: 'Solid',
    finish: 'High Sheen',
    lightFastness: 6,
    images: { primary: '/images/fabric-satin.jpg' },
    minOrder: 30,
    priceCategory: 3,
  },
  {
    id: 'sat-006',
    name: 'Rose Gold Satin',
    category: 'satin',
    sku: 'SAT-RSG-300',
    width: 300,
    weight: 180,
    composition: { polyester: 80, metallic: 5, viscose: 15 },
    usageAreas: ['event-decor', 'cushions', 'tablecloth'],
    washingInstructions: ['hand-wash', 'do-not-bleach', 'iron-low'],
    colors: ['Rose Gold', 'Copper', 'Blush Gold'],
    pattern: 'Solid',
    finish: 'Metallic Sheen',
    lightFastness: 4,
    images: { primary: '/images/fabric-satin.jpg' },
    minOrder: 25,
    priceCategory: 4,
    featured: true,
  },

  // ============ LINEN COLLECTION ============
  {
    id: 'lin-001',
    name: 'Belgian Natural Linen',
    category: 'linen',
    sku: 'LIN-NAT-150',
    width: 150,
    weight: 220,
    composition: { linen: 100 },
    usageAreas: ['tablecloth', 'curtains', 'bedding'],
    washingInstructions: ['machine-wash-40', 'tumble-dry-low', 'iron-high'],
    colors: ['Natural', 'Oatmeal', 'Flax'],
    pattern: 'Plain Weave',
    finish: 'Stonewashed',
    lightFastness: 6,
    images: { primary: '/images/fabric-linen.jpg' },
    minOrder: 25,
    priceCategory: 3,
    bestseller: true,
  },
  {
    id: 'lin-002',
    name: 'White Belgian Linen',
    category: 'linen',
    sku: 'LIN-WHT-150',
    width: 150,
    weight: 210,
    composition: { linen: 100 },
    usageAreas: ['tablecloth', 'bedding', 'curtains'],
    washingInstructions: ['machine-wash-60', 'tumble-dry-low', 'iron-high'],
    colors: ['White', 'Bright White', 'Optical White'],
    pattern: 'Plain Weave',
    finish: 'Crisp',
    lightFastness: 7,
    images: { primary: '/images/fabric-linen.jpg' },
    minOrder: 25,
    priceCategory: 3,
  },
  {
    id: 'lin-003',
    name: 'Sage Green Linen',
    category: 'linen',
    sku: 'LIN-SAG-150',
    width: 150,
    weight: 230,
    composition: { linen: 85, cotton: 15 },
    usageAreas: ['curtains', 'tablecloth', 'cushions'],
    washingInstructions: ['machine-wash-40', 'tumble-dry-low', 'iron-high'],
    colors: ['Sage', 'Olive', 'Moss'],
    pattern: 'Plain Weave',
    finish: 'Softened',
    lightFastness: 5,
    images: { primary: '/images/fabric-linen.jpg' },
    minOrder: 20,
    priceCategory: 3,
    new: true,
  },
  {
    id: 'lin-004',
    name: 'Dusty Blue Linen',
    category: 'linen',
    sku: 'LIN-DBL-150',
    width: 150,
    weight: 220,
    composition: { linen: 100 },
    usageAreas: ['bedding', 'curtains', 'tablecloth'],
    washingInstructions: ['machine-wash-40', 'tumble-dry-low', 'iron-high'],
    colors: ['Dusty Blue', 'Sky', 'Powder Blue'],
    pattern: 'Plain Weave',
    finish: 'Stonewashed',
    lightFastness: 5,
    images: { primary: '/images/fabric-linen.jpg' },
    minOrder: 25,
    priceCategory: 3,
  },
  {
    id: 'lin-005',
    name: 'Terracotta Linen',
    category: 'linen',
    sku: 'LIN-TER-150',
    width: 150,
    weight: 225,
    composition: { linen: 90, cotton: 10 },
    usageAreas: ['curtains', 'cushions', 'tablecloth'],
    washingInstructions: ['machine-wash-40', 'tumble-dry-low', 'iron-high'],
    colors: ['Terracotta', 'Rust', 'Sienna'],
    pattern: 'Plain Weave',
    finish: 'Softened',
    lightFastness: 5,
    images: { primary: '/images/fabric-linen.jpg' },
    minOrder: 20,
    priceCategory: 3,
    featured: true,
  },

  // ============ JACQUARD COLLECTION ============
  {
    id: 'jac-001',
    name: 'Royal Damask Jacquard',
    category: 'jacquard',
    sku: 'JAC-DMK-280',
    width: 280,
    weight: 400,
    composition: { cotton: 70, polyester: 30 },
    usageAreas: ['upholstery', 'curtains', 'cushions'],
    washingInstructions: ['dry-clean-only', 'do-not-bleach', 'professional-care'],
    colors: ['Navy/Gold', 'Burgundy/Gold', 'Forest/Silver'],
    pattern: 'Damask Floral',
    finish: 'Woven',
    martindale: 35000,
    lightFastness: 5,
    images: { primary: '/images/fabric-jacquard.jpg' },
    minOrder: 40,
    priceCategory: 4,
    featured: true,
    bestseller: true,
  },
  {
    id: 'jac-002',
    name: 'Geometric Modern Jacquard',
    category: 'jacquard',
    sku: 'JAC-GEO-280',
    width: 280,
    weight: 380,
    composition: { polyester: 60, cotton: 40 },
    usageAreas: ['upholstery', 'cushions', 'curtains'],
    washingInstructions: ['dry-clean-only', 'do-not-bleach', 'iron-low'],
    colors: ['Grey/White', 'Navy/Ivory', 'Black/Gold'],
    pattern: 'Geometric',
    finish: 'Woven',
    martindale: 40000,
    lightFastness: 5,
    fireRetardant: true,
    images: { primary: '/images/fabric-jacquard.jpg' },
    minOrder: 35,
    priceCategory: 4,
    new: true,
  },
  {
    id: 'jac-003',
    name: 'Baroque Scroll Jacquard',
    category: 'jacquard',
    sku: 'JAC-BRQ-280',
    width: 280,
    weight: 420,
    composition: { cotton: 65, viscose: 25, polyester: 10 },
    usageAreas: ['upholstery', 'wall-panels', 'cushions'],
    washingInstructions: ['dry-clean-only', 'do-not-bleach', 'professional-care'],
    colors: ['Cream/Gold', 'Silver/Grey', 'Bronze/Brown'],
    pattern: 'Baroque Scroll',
    finish: 'Woven',
    martindale: 32000,
    lightFastness: 5,
    images: { primary: '/images/fabric-jacquard.jpg' },
    minOrder: 40,
    priceCategory: 5,
  },
  {
    id: 'jac-004',
    name: 'Floral Garden Jacquard',
    category: 'jacquard',
    sku: 'JAC-FLR-280',
    width: 280,
    weight: 370,
    composition: { cotton: 60, polyester: 40 },
    usageAreas: ['curtains', 'cushions', 'bedding'],
    washingInstructions: ['dry-clean-only', 'do-not-bleach', 'iron-low'],
    colors: ['Ivory/Rose', 'Sage/Cream', 'Blue/White'],
    pattern: 'Floral',
    finish: 'Woven',
    martindale: 28000,
    lightFastness: 4,
    images: { primary: '/images/fabric-jacquard.jpg' },
    minOrder: 30,
    priceCategory: 3,
  },

  // ============ SILK BLEND COLLECTION ============
  {
    id: 'slk-001',
    name: 'Pure Ivory Silk',
    category: 'silk',
    sku: 'SLK-IVY-140',
    width: 140,
    weight: 90,
    composition: { silk: 65, cotton: 35 },
    usageAreas: ['curtains', 'bedding', 'event-decor'],
    washingInstructions: ['dry-clean-only', 'professional-care'],
    colors: ['Ivory', 'Cream', 'Pearl'],
    pattern: 'Plain Weave',
    finish: 'Natural Sheen',
    lightFastness: 3,
    images: { primary: '/images/fabric-silk.jpg' },
    minOrder: 20,
    priceCategory: 5,
    featured: true,
  },
  {
    id: 'slk-002',
    name: 'Blush Pink Silk',
    category: 'silk',
    sku: 'SLK-BLS-140',
    width: 140,
    weight: 85,
    composition: { silk: 60, cotton: 40 },
    usageAreas: ['curtains', 'bedding', 'event-decor'],
    washingInstructions: ['dry-clean-only', 'professional-care'],
    colors: ['Blush', 'Rose', 'Petal'],
    pattern: 'Plain Weave',
    finish: 'Natural Sheen',
    lightFastness: 3,
    images: { primary: '/images/fabric-silk.jpg' },
    minOrder: 20,
    priceCategory: 5,
  },
  {
    id: 'slk-003',
    name: 'Champagne Silk',
    category: 'silk',
    sku: 'SLK-CHP-140',
    width: 140,
    weight: 88,
    composition: { silk: 70, cotton: 30 },
    usageAreas: ['curtains', 'event-decor', 'bedding'],
    washingInstructions: ['dry-clean-only', 'professional-care'],
    colors: ['Champagne', 'Gold Mist', 'Honey'],
    pattern: 'Plain Weave',
    finish: 'Lustrous',
    lightFastness: 4,
    images: { primary: '/images/fabric-silk.jpg' },
    minOrder: 15,
    priceCategory: 5,
    bestseller: true,
  },
  {
    id: 'slk-004',
    name: 'Dove Grey Silk',
    category: 'silk',
    sku: 'SLK-DVG-140',
    width: 140,
    weight: 92,
    composition: { silk: 65, cotton: 35 },
    usageAreas: ['curtains', 'bedding', 'cushions'],
    washingInstructions: ['dry-clean-only', 'professional-care'],
    colors: ['Dove Grey', 'Silver', 'Platinum'],
    pattern: 'Plain Weave',
    finish: 'Natural Sheen',
    lightFastness: 4,
    images: { primary: '/images/fabric-silk.jpg' },
    minOrder: 20,
    priceCategory: 5,
  },
  {
    id: 'slk-005',
    name: 'Soft Gold Silk',
    category: 'silk',
    sku: 'SLK-GLD-140',
    width: 140,
    weight: 95,
    composition: { silk: 75, metallic: 5, cotton: 20 },
    usageAreas: ['event-decor', 'curtains', 'cushions'],
    washingInstructions: ['dry-clean-only', 'professional-care'],
    colors: ['Soft Gold', 'Antique Gold', 'Bronze'],
    pattern: 'Plain Weave',
    finish: 'Metallic Sheen',
    lightFastness: 4,
    images: { primary: '/images/fabric-silk.jpg' },
    minOrder: 15,
    priceCategory: 5,
    new: true,
  },

  // ============ CHENILLE COLLECTION ============
  {
    id: 'chn-001',
    name: 'Taupe Chenille',
    category: 'chenille',
    sku: 'CHN-TAU-280',
    width: 280,
    weight: 450,
    composition: { polyester: 100 },
    usageAreas: ['upholstery', 'cushions', 'throws'],
    washingInstructions: ['dry-clean-only', 'do-not-bleach'],
    colors: ['Taupe', 'Mushroom', 'Stone'],
    pattern: 'Solid',
    finish: 'Plush',
    martindale: 50000,
    lightFastness: 5,
    images: { primary: '/images/fabric-chenille.jpg' },
    minOrder: 40,
    priceCategory: 3,
    bestseller: true,
  },
  {
    id: 'chn-002',
    name: 'Sage Chenille',
    category: 'chenille',
    sku: 'CHN-SAG-280',
    width: 280,
    weight: 440,
    composition: { polyester: 100 },
    usageAreas: ['upholstery', 'cushions', 'throws'],
    washingInstructions: ['dry-clean-only', 'do-not-bleach'],
    colors: ['Sage', 'Moss', 'Fern'],
    pattern: 'Solid',
    finish: 'Plush',
    martindale: 48000,
    lightFastness: 5,
    images: { primary: '/images/fabric-chenille.jpg' },
    minOrder: 40,
    priceCategory: 3,
    new: true,
  },
  {
    id: 'chn-003',
    name: 'Dusty Rose Chenille',
    category: 'chenille',
    sku: 'CHN-DRS-280',
    width: 280,
    weight: 460,
    composition: { polyester: 90, viscose: 10 },
    usageAreas: ['upholstery', 'cushions', 'headboards'],
    washingInstructions: ['dry-clean-only', 'do-not-bleach'],
    colors: ['Dusty Rose', 'Blush', 'Mauve'],
    pattern: 'Solid',
    finish: 'Plush',
    martindale: 45000,
    lightFastness: 5,
    images: { primary: '/images/fabric-chenille.jpg' },
    minOrder: 35,
    priceCategory: 3,
  },
  {
    id: 'chn-004',
    name: 'Slate Chenille',
    category: 'chenille',
    sku: 'CHN-SLT-280',
    width: 280,
    weight: 470,
    composition: { polyester: 100 },
    usageAreas: ['upholstery', 'cushions', 'throws'],
    washingInstructions: ['dry-clean-only', 'do-not-bleach'],
    colors: ['Slate', 'Charcoal', 'Graphite'],
    pattern: 'Solid',
    finish: 'Plush',
    martindale: 55000,
    lightFastness: 6,
    fireRetardant: true,
    images: { primary: '/images/fabric-chenille.jpg' },
    minOrder: 40,
    priceCategory: 4,
    featured: true,
  },
  {
    id: 'chn-005',
    name: 'Cream Chenille',
    category: 'chenille',
    sku: 'CHN-CRM-280',
    width: 280,
    weight: 445,
    composition: { polyester: 100 },
    usageAreas: ['upholstery', 'cushions', 'throws'],
    washingInstructions: ['dry-clean-only', 'do-not-bleach'],
    colors: ['Cream', 'Ivory', 'Natural'],
    pattern: 'Solid',
    finish: 'Plush',
    martindale: 48000,
    lightFastness: 5,
    images: { primary: '/images/fabric-chenille.jpg' },
    minOrder: 35,
    priceCategory: 3,
  },
  {
    id: 'chn-006',
    name: 'Terracotta Chenille',
    category: 'chenille',
    sku: 'CHN-TER-280',
    width: 280,
    weight: 455,
    composition: { polyester: 95, viscose: 5 },
    usageAreas: ['upholstery', 'cushions', 'throws'],
    washingInstructions: ['dry-clean-only', 'do-not-bleach'],
    colors: ['Terracotta', 'Rust', 'Burnt Orange'],
    pattern: 'Solid',
    finish: 'Plush',
    martindale: 46000,
    lightFastness: 5,
    images: { primary: '/images/fabric-chenille.jpg' },
    minOrder: 40,
    priceCategory: 3,
  },

  // ============ ORGANZA COLLECTION ============
  {
    id: 'org-001',
    name: 'Crystal White Organza',
    category: 'organza',
    sku: 'ORG-CRY-300',
    width: 300,
    weight: 45,
    composition: { polyester: 100 },
    usageAreas: ['curtains', 'event-decor'],
    washingInstructions: ['hand-wash', 'iron-low'],
    colors: ['Crystal', 'White', 'Ice'],
    pattern: 'Plain',
    finish: 'Sheer',
    lightFastness: 6,
    images: { primary: '/images/fabric-organza.jpg' },
    minOrder: 50,
    priceCategory: 2,
    bestseller: true,
  },
  {
    id: 'org-002',
    name: 'Champagne Organza',
    category: 'organza',
    sku: 'ORG-CHP-300',
    width: 300,
    weight: 42,
    composition: { polyester: 100 },
    usageAreas: ['curtains', 'event-decor'],
    washingInstructions: ['hand-wash', 'iron-low'],
    colors: ['Champagne', 'Gold Mist', 'Honey'],
    pattern: 'Plain',
    finish: 'Sheer',
    lightFastness: 5,
    images: { primary: '/images/fabric-organza.jpg' },
    minOrder: 50,
    priceCategory: 2,
  },
  {
    id: 'org-003',
    name: 'Blush Organza',
    category: 'organza',
    sku: 'ORG-BLS-300',
    width: 300,
    weight: 44,
    composition: { polyester: 100 },
    usageAreas: ['curtains', 'event-decor'],
    washingInstructions: ['hand-wash', 'iron-low'],
    colors: ['Blush', 'Rose', 'Peach'],
    pattern: 'Plain',
    finish: 'Sheer',
    lightFastness: 4,
    images: { primary: '/images/fabric-organza.jpg' },
    minOrder: 50,
    priceCategory: 2,
    new: true,
  },
  {
    id: 'org-004',
    name: 'Lavender Organza',
    category: 'organza',
    sku: 'ORG-LAV-300',
    width: 300,
    weight: 43,
    composition: { polyester: 100 },
    usageAreas: ['curtains', 'event-decor'],
    washingInstructions: ['hand-wash', 'iron-low'],
    colors: ['Lavender', 'Lilac', 'Wisteria'],
    pattern: 'Plain',
    finish: 'Sheer',
    lightFastness: 4,
    images: { primary: '/images/fabric-organza.jpg' },
    minOrder: 50,
    priceCategory: 2,
  },
  {
    id: 'org-005',
    name: 'Mint Organza',
    category: 'organza',
    sku: 'ORG-MNT-300',
    width: 300,
    weight: 44,
    composition: { polyester: 100 },
    usageAreas: ['curtains', 'event-decor'],
    washingInstructions: ['hand-wash', 'iron-low'],
    colors: ['Mint', 'Seafoam', 'Aqua'],
    pattern: 'Plain',
    finish: 'Sheer',
    lightFastness: 4,
    images: { primary: '/images/fabric-organza.jpg' },
    minOrder: 50,
    priceCategory: 2,
  },
  {
    id: 'org-006',
    name: 'Gold Shimmer Organza',
    category: 'organza',
    sku: 'ORG-GLD-300',
    width: 300,
    weight: 48,
    composition: { polyester: 95, metallic: 5 },
    usageAreas: ['event-decor', 'curtains'],
    washingInstructions: ['hand-wash', 'iron-low'],
    colors: ['Gold', 'Antique Gold', 'Copper'],
    pattern: 'Plain',
    finish: 'Shimmer',
    lightFastness: 5,
    images: { primary: '/images/fabric-organza.jpg' },
    minOrder: 40,
    priceCategory: 3,
    featured: true,
  },

  // ============ TAFFETA COLLECTION ============
  {
    id: 'taf-001',
    name: 'Bronze Taffeta',
    category: 'taffeta',
    sku: 'TAF-BRZ-150',
    width: 150,
    weight: 120,
    composition: { polyester: 100 },
    usageAreas: ['curtains', 'event-decor', 'tablecloth'],
    washingInstructions: ['machine-wash-30', 'do-not-tumble-dry', 'iron-medium'],
    colors: ['Bronze', 'Copper', 'Antique Gold'],
    pattern: 'Plain',
    finish: 'Crisp',
    lightFastness: 5,
    images: { primary: '/images/fabric-taffeta.jpg' },
    minOrder: 30,
    priceCategory: 2,
    bestseller: true,
  },
  {
    id: 'taf-002',
    name: 'Burgundy Taffeta',
    category: 'taffeta',
    sku: 'TAF-BRG-150',
    width: 150,
    weight: 125,
    composition: { polyester: 100 },
    usageAreas: ['curtains', 'event-decor', 'tablecloth'],
    washingInstructions: ['machine-wash-30', 'do-not-tumble-dry', 'iron-medium'],
    colors: ['Burgundy', 'Wine', 'Merlot'],
    pattern: 'Plain',
    finish: 'Crisp',
    lightFastness: 5,
    images: { primary: '/images/fabric-taffeta.jpg' },
    minOrder: 30,
    priceCategory: 2,
  },
  {
    id: 'taf-003',
    name: 'Hunter Green Taffeta',
    category: 'taffeta',
    sku: 'TAF-HGR-150',
    width: 150,
    weight: 122,
    composition: { polyester: 100 },
    usageAreas: ['curtains', 'event-decor', 'tablecloth'],
    washingInstructions: ['machine-wash-30', 'do-not-tumble-dry', 'iron-medium'],
    colors: ['Hunter Green', 'Forest', 'Emerald'],
    pattern: 'Plain',
    finish: 'Crisp',
    lightFastness: 5,
    images: { primary: '/images/fabric-taffeta.jpg' },
    minOrder: 30,
    priceCategory: 2,
  },
  {
    id: 'taf-004',
    name: 'Royal Blue Taffeta',
    category: 'taffeta',
    sku: 'TAF-RBL-150',
    width: 150,
    weight: 118,
    composition: { polyester: 100 },
    usageAreas: ['curtains', 'event-decor'],
    washingInstructions: ['machine-wash-30', 'do-not-tumble-dry', 'iron-medium'],
    colors: ['Royal Blue', 'Sapphire', 'Cobalt'],
    pattern: 'Plain',
    finish: 'Crisp',
    lightFastness: 5,
    images: { primary: '/images/fabric-taffeta.jpg' },
    minOrder: 30,
    priceCategory: 2,
    new: true,
  },
  {
    id: 'taf-005',
    name: 'Gold Taffeta',
    category: 'taffeta',
    sku: 'TAF-GLD-150',
    width: 150,
    weight: 124,
    composition: { polyester: 95, metallic: 5 },
    usageAreas: ['event-decor', 'tablecloth', 'curtains'],
    washingInstructions: ['hand-wash', 'do-not-tumble-dry', 'iron-low'],
    colors: ['Gold', 'Champagne Gold', 'Antique Gold'],
    pattern: 'Plain',
    finish: 'Metallic',
    lightFastness: 5,
    images: { primary: '/images/fabric-taffeta.jpg' },
    minOrder: 25,
    priceCategory: 3,
  },
  {
    id: 'taf-006',
    name: 'Silver Taffeta',
    category: 'taffeta',
    sku: 'TAF-SLV-150',
    width: 150,
    weight: 126,
    composition: { polyester: 95, metallic: 5 },
    usageAreas: ['event-decor', 'tablecloth', 'curtains'],
    washingInstructions: ['hand-wash', 'do-not-tumble-dry', 'iron-low'],
    colors: ['Silver', 'Platinum', 'Pewter'],
    pattern: 'Plain',
    finish: 'Metallic',
    lightFastness: 5,
    images: { primary: '/images/fabric-taffeta.jpg' },
    minOrder: 25,
    priceCategory: 3,
    featured: true,
  },

  // ============ BROCADE COLLECTION ============
  {
    id: 'brc-001',
    name: 'Gold Burgundy Brocade',
    category: 'brocade',
    sku: 'BRC-GBR-140',
    width: 140,
    weight: 320,
    composition: { silk: 55, metallic: 45 },
    usageAreas: ['upholstery', 'wall-panels', 'cushions', 'event-decor'],
    washingInstructions: ['dry-clean-only', 'professional-care'],
    colors: ['Gold/Burgundy', 'Gold/Wine', 'Gold/Plum'],
    pattern: 'Floral Motif',
    finish: 'Woven',
    martindale: 25000,
    lightFastness: 4,
    images: { primary: '/images/fabric-brocade.jpg' },
    minOrder: 15,
    priceCategory: 5,
    featured: true,
    bestseller: true,
  },
  {
    id: 'brc-002',
    name: 'Silver Navy Brocade',
    category: 'brocade',
    sku: 'BRC-SNV-140',
    width: 140,
    weight: 310,
    composition: { silk: 50, metallic: 50 },
    usageAreas: ['upholstery', 'wall-panels', 'cushions'],
    washingInstructions: ['dry-clean-only', 'professional-care'],
    colors: ['Silver/Navy', 'Silver/Royal', 'Silver/Midnight'],
    pattern: 'Medallion',
    finish: 'Woven',
    martindale: 23000,
    lightFastness: 4,
    images: { primary: '/images/fabric-brocade.jpg' },
    minOrder: 15,
    priceCategory: 5,
  },
  {
    id: 'brc-003',
    name: 'Bronze Emerald Brocade',
    category: 'brocade',
    sku: 'BRC-BEM-140',
    width: 140,
    weight: 325,
    composition: { silk: 55, metallic: 45 },
    usageAreas: ['upholstery', 'wall-panels', 'event-decor'],
    washingInstructions: ['dry-clean-only', 'professional-care'],
    colors: ['Bronze/Emerald', 'Bronze/Forest', 'Bronze/Teal'],
    pattern: 'Paisley',
    finish: 'Woven',
    martindale: 24000,
    lightFastness: 4,
    images: { primary: '/images/fabric-brocade.jpg' },
    minOrder: 15,
    priceCategory: 5,
    new: true,
  },
  {
    id: 'brc-004',
    name: 'Ivory Gold Brocade',
    category: 'brocade',
    sku: 'BRC-IVG-140',
    width: 140,
    weight: 305,
    composition: { silk: 60, metallic: 40 },
    usageAreas: ['event-decor', 'cushions', 'wall-panels'],
    washingInstructions: ['dry-clean-only', 'professional-care'],
    colors: ['Ivory/Gold', 'Cream/Gold', 'Pearl/Gold'],
    pattern: 'Scroll',
    finish: 'Woven',
    martindale: 22000,
    lightFastness: 3,
    images: { primary: '/images/fabric-brocade.jpg' },
    minOrder: 15,
    priceCategory: 5,
  },

  // ============ DAMASK COLLECTION ============
  {
    id: 'dam-001',
    name: 'White Classic Damask',
    category: 'damask',
    sku: 'DAM-WHT-280',
    width: 280,
    weight: 350,
    composition: { cotton: 80, silk: 20 },
    usageAreas: ['tablecloth', 'bedding', 'curtains'],
    washingInstructions: ['machine-wash-40', 'tumble-dry-low', 'iron-high'],
    colors: ['White', 'Bright White', 'Snow'],
    pattern: 'Classic Damask',
    finish: 'Mercerized',
    lightFastness: 7,
    images: { primary: '/images/fabric-damask.jpg' },
    minOrder: 25,
    priceCategory: 4,
    bestseller: true,
  },
  {
    id: 'dam-002',
    name: 'Ivory Damask',
    category: 'damask',
    sku: 'DAM-IVY-280',
    width: 280,
    weight: 345,
    composition: { cotton: 85, silk: 15 },
    usageAreas: ['tablecloth', 'bedding', 'curtains'],
    washingInstructions: ['machine-wash-40', 'tumble-dry-low', 'iron-high'],
    colors: ['Ivory', 'Cream', 'Ecru'],
    pattern: 'Classic Damask',
    finish: 'Mercerized',
    lightFastness: 6,
    images: { primary: '/images/fabric-damask.jpg' },
    minOrder: 25,
    priceCategory: 4,
  },
  {
    id: 'dam-003',
    name: 'Champagne Damask',
    category: 'damask',
    sku: 'DAM-CHP-280',
    width: 280,
    weight: 355,
    composition: { cotton: 75, silk: 25 },
    usageAreas: ['tablecloth', 'event-decor', 'bedding'],
    washingInstructions: ['dry-clean-only', 'iron-medium'],
    colors: ['Champagne', 'Gold Mist', 'Honey'],
    pattern: 'Floral Damask',
    finish: 'Sateen',
    lightFastness: 5,
    images: { primary: '/images/fabric-damask.jpg' },
    minOrder: 25,
    priceCategory: 4,
    featured: true,
  },
  {
    id: 'dam-004',
    name: 'Blush Damask',
    category: 'damask',
    sku: 'DAM-BLS-280',
    width: 280,
    weight: 340,
    composition: { cotton: 80, silk: 20 },
    usageAreas: ['bedding', 'curtains', 'tablecloth'],
    washingInstructions: ['machine-wash-40', 'tumble-dry-low', 'iron-medium'],
    colors: ['Blush', 'Rose', 'Dusty Pink'],
    pattern: 'Classic Damask',
    finish: 'Mercerized',
    lightFastness: 5,
    images: { primary: '/images/fabric-damask.jpg' },
    minOrder: 25,
    priceCategory: 4,
    new: true,
  },
  {
    id: 'dam-005',
    name: 'Sage Damask',
    category: 'damask',
    sku: 'DAM-SAG-280',
    width: 280,
    weight: 348,
    composition: { cotton: 80, silk: 20 },
    usageAreas: ['tablecloth', 'curtains', 'bedding'],
    washingInstructions: ['machine-wash-40', 'tumble-dry-low', 'iron-high'],
    colors: ['Sage', 'Mint', 'Seafoam'],
    pattern: 'Classic Damask',
    finish: 'Mercerized',
    lightFastness: 5,
    images: { primary: '/images/fabric-damask.jpg' },
    minOrder: 25,
    priceCategory: 4,
  },

  // ============ SUEDE COLLECTION ============
  {
    id: 'sud-001',
    name: 'Camel Microsuede',
    category: 'suede',
    sku: 'SUD-CML-140',
    width: 140,
    weight: 280,
    composition: { polyester: 100 },
    usageAreas: ['upholstery', 'headboards', 'cushions'],
    washingInstructions: ['dry-clean-only', 'do-not-bleach'],
    colors: ['Camel', 'Tan', 'Sand'],
    pattern: 'Solid',
    finish: 'Brushed',
    martindale: 60000,
    lightFastness: 5,
    images: { primary: '/images/fabric-suede.jpg' },
    minOrder: 30,
    priceCategory: 3,
    bestseller: true,
  },
  {
    id: 'sud-002',
    name: 'Charcoal Microsuede',
    category: 'suede',
    sku: 'SUD-CHR-140',
    width: 140,
    weight: 285,
    composition: { polyester: 100 },
    usageAreas: ['upholstery', 'headboards', 'wall-panels'],
    washingInstructions: ['dry-clean-only', 'do-not-bleach'],
    colors: ['Charcoal', 'Graphite', 'Slate'],
    pattern: 'Solid',
    finish: 'Brushed',
    martindale: 65000,
    lightFastness: 6,
    fireRetardant: true,
    images: { primary: '/images/fabric-suede.jpg' },
    minOrder: 30,
    priceCategory: 4,
    featured: true,
  },
  {
    id: 'sud-003',
    name: 'Olive Microsuede',
    category: 'suede',
    sku: 'SUD-OLV-140',
    width: 140,
    weight: 275,
    composition: { polyester: 100 },
    usageAreas: ['upholstery', 'cushions', 'headboards'],
    washingInstructions: ['dry-clean-only', 'do-not-bleach'],
    colors: ['Olive', 'Moss', 'Forest'],
    pattern: 'Solid',
    finish: 'Brushed',
    martindale: 58000,
    lightFastness: 5,
    images: { primary: '/images/fabric-suede.jpg' },
    minOrder: 30,
    priceCategory: 3,
  },
  {
    id: 'sud-004',
    name: 'Burgundy Microsuede',
    category: 'suede',
    sku: 'SUD-BRG-140',
    width: 140,
    weight: 282,
    composition: { polyester: 100 },
    usageAreas: ['upholstery', 'headboards', 'cushions'],
    washingInstructions: ['dry-clean-only', 'do-not-bleach'],
    colors: ['Burgundy', 'Wine', 'Merlot'],
    pattern: 'Solid',
    finish: 'Brushed',
    martindale: 62000,
    lightFastness: 5,
    images: { primary: '/images/fabric-suede.jpg' },
    minOrder: 30,
    priceCategory: 3,
    new: true,
  },
  {
    id: 'sud-005',
    name: 'Navy Microsuede',
    category: 'suede',
    sku: 'SUD-NVY-140',
    width: 140,
    weight: 288,
    composition: { polyester: 100 },
    usageAreas: ['upholstery', 'headboards', 'wall-panels'],
    washingInstructions: ['dry-clean-only', 'do-not-bleach'],
    colors: ['Navy', 'Midnight', 'Indigo'],
    pattern: 'Solid',
    finish: 'Brushed',
    martindale: 63000,
    lightFastness: 6,
    images: { primary: '/images/fabric-suede.jpg' },
    minOrder: 30,
    priceCategory: 3,
  },
  {
    id: 'sud-006',
    name: 'Stone Microsuede',
    category: 'suede',
    sku: 'SUD-STN-140',
    width: 140,
    weight: 278,
    composition: { polyester: 100 },
    usageAreas: ['upholstery', 'cushions', 'headboards'],
    washingInstructions: ['dry-clean-only', 'do-not-bleach'],
    colors: ['Stone', 'Pebble', 'Gravel'],
    pattern: 'Solid',
    finish: 'Brushed',
    martindale: 59000,
    lightFastness: 5,
    images: { primary: '/images/fabric-suede.jpg' },
    minOrder: 30,
    priceCategory: 3,
  },

  // ============ BLACKOUT COLLECTION ============
  {
    id: 'blk-001',
    name: 'Premium White Blackout',
    category: 'blackout',
    sku: 'BLK-WHT-280',
    width: 280,
    weight: 320,
    composition: { polyester: 100 },
    usageAreas: ['curtains'],
    washingInstructions: ['machine-wash-30', 'do-not-tumble-dry', 'iron-low'],
    colors: ['White', 'Off-White', 'Ivory'],
    pattern: 'Solid',
    finish: '3-Pass Coating',
    lightFastness: 7,
    fireRetardant: true,
    images: { primary: '/images/fabric-velvet.jpg' },
    minOrder: 40,
    priceCategory: 3,
    bestseller: true,
  },
  {
    id: 'blk-002',
    name: 'Premium Grey Blackout',
    category: 'blackout',
    sku: 'BLK-GRY-280',
    width: 280,
    weight: 325,
    composition: { polyester: 100 },
    usageAreas: ['curtains'],
    washingInstructions: ['machine-wash-30', 'do-not-tumble-dry', 'iron-low'],
    colors: ['Light Grey', 'Medium Grey', 'Charcoal'],
    pattern: 'Solid',
    finish: '3-Pass Coating',
    lightFastness: 7,
    fireRetardant: true,
    images: { primary: '/images/fabric-velvet.jpg' },
    minOrder: 40,
    priceCategory: 3,
  },
  {
    id: 'blk-003',
    name: 'Premium Navy Blackout',
    category: 'blackout',
    sku: 'BLK-NVY-280',
    width: 280,
    weight: 330,
    composition: { polyester: 100 },
    usageAreas: ['curtains'],
    washingInstructions: ['machine-wash-30', 'do-not-tumble-dry', 'iron-low'],
    colors: ['Navy', 'Midnight', 'Indigo'],
    pattern: 'Solid',
    finish: '3-Pass Coating',
    lightFastness: 7,
    fireRetardant: true,
    images: { primary: '/images/fabric-velvet.jpg' },
    minOrder: 40,
    priceCategory: 3,
    featured: true,
  },
  {
    id: 'blk-004',
    name: 'Premium Beige Blackout',
    category: 'blackout',
    sku: 'BLK-BGE-280',
    width: 280,
    weight: 318,
    composition: { polyester: 100 },
    usageAreas: ['curtains'],
    washingInstructions: ['machine-wash-30', 'do-not-tumble-dry', 'iron-low'],
    colors: ['Beige', 'Taupe', 'Sand'],
    pattern: 'Solid',
    finish: '3-Pass Coating',
    lightFastness: 6,
    fireRetardant: true,
    images: { primary: '/images/fabric-velvet.jpg' },
    minOrder: 40,
    priceCategory: 3,
    new: true,
  },

  // ============ SHEER COLLECTION ============
  {
    id: 'shr-001',
    name: 'White Voile Sheer',
    category: 'sheer',
    sku: 'SHR-WHT-300',
    width: 300,
    weight: 55,
    composition: { polyester: 100 },
    usageAreas: ['curtains'],
    washingInstructions: ['machine-wash-30', 'do-not-tumble-dry', 'iron-low'],
    colors: ['White', 'Pure White', 'Snow White'],
    pattern: 'Plain',
    finish: 'Soft Drape',
    lightFastness: 6,
    images: { primary: '/images/fabric-organza.jpg' },
    minOrder: 50,
    priceCategory: 1,
    bestseller: true,
  },
  {
    id: 'shr-002',
    name: 'Ivory Voile Sheer',
    category: 'sheer',
    sku: 'SHR-IVY-300',
    width: 300,
    weight: 52,
    composition: { polyester: 100 },
    usageAreas: ['curtains'],
    washingInstructions: ['machine-wash-30', 'do-not-tumble-dry', 'iron-low'],
    colors: ['Ivory', 'Cream', 'Natural'],
    pattern: 'Plain',
    finish: 'Soft Drape',
    lightFastness: 5,
    images: { primary: '/images/fabric-organza.jpg' },
    minOrder: 50,
    priceCategory: 1,
  },
  {
    id: 'shr-003',
    name: 'Linen Look Sheer',
    category: 'sheer',
    sku: 'SHR-LNL-300',
    width: 300,
    weight: 68,
    composition: { polyester: 85, linen: 15 },
    usageAreas: ['curtains'],
    washingInstructions: ['machine-wash-30', 'do-not-tumble-dry', 'iron-medium'],
    colors: ['Natural', 'Oatmeal', 'Flax'],
    pattern: 'Textured',
    finish: 'Linen Texture',
    lightFastness: 5,
    images: { primary: '/images/fabric-organza.jpg' },
    minOrder: 40,
    priceCategory: 2,
    featured: true,
  },
  {
    id: 'shr-004',
    name: 'Embroidered Floral Sheer',
    category: 'sheer',
    sku: 'SHR-EMB-300',
    width: 300,
    weight: 75,
    composition: { polyester: 100 },
    usageAreas: ['curtains'],
    washingInstructions: ['hand-wash', 'do-not-tumble-dry', 'iron-low'],
    colors: ['White/Silver', 'Ivory/Gold', 'Grey/White'],
    pattern: 'Embroidered Floral',
    finish: 'Decorative',
    lightFastness: 4,
    images: { primary: '/images/fabric-organza.jpg' },
    minOrder: 35,
    priceCategory: 3,
    new: true,
  },
]

// Helper function to format composition as string
export function formatComposition(composition: FabricComposition): string {
  const parts: string[] = []
  if (composition.cotton) parts.push(`${composition.cotton}% Cotton`)
  if (composition.polyester) parts.push(`${composition.polyester}% Polyester`)
  if (composition.viscose) parts.push(`${composition.viscose}% Viscose`)
  if (composition.silk) parts.push(`${composition.silk}% Silk`)
  if (composition.linen) parts.push(`${composition.linen}% Linen`)
  if (composition.wool) parts.push(`${composition.wool}% Wool`)
  if (composition.acrylic) parts.push(`${composition.acrylic}% Acrylic`)
  if (composition.nylon) parts.push(`${composition.nylon}% Nylon`)
  if (composition.metallic) parts.push(`${composition.metallic}% Metallic`)
  return parts.join(', ')
}

// Get all unique categories
export function getCategories(): FabricCategory[] {
  return [...new Set(FABRIC_DATA.map(f => f.category))]
}

// Get products by category
export function getProductsByCategory(category: FabricCategory): FabricProduct[] {
  return FABRIC_DATA.filter(f => f.category === category)
}

// Get featured products
export function getFeaturedProducts(): FabricProduct[] {
  return FABRIC_DATA.filter(f => f.featured)
}

// Get bestsellers
export function getBestsellers(): FabricProduct[] {
  return FABRIC_DATA.filter(f => f.bestseller)
}

// Get new arrivals
export function getNewArrivals(): FabricProduct[] {
  return FABRIC_DATA.filter(f => f.new)
}

// Get product by ID
export function getProductById(id: string): FabricProduct | undefined {
  return FABRIC_DATA.find(f => f.id === id)
}

// Filter products with multiple criteria
export interface FilterCriteria {
  category?: FabricCategory
  usageArea?: UsageArea
  minWeight?: number
  maxWeight?: number
  minWidth?: number
  maxWidth?: number
  priceCategory?: number
  fireRetardant?: boolean
  search?: string
}

export function filterProducts(criteria: FilterCriteria): FabricProduct[] {
  return FABRIC_DATA.filter(product => {
    if (criteria.category && product.category !== criteria.category) return false
    if (criteria.usageArea && !product.usageAreas.includes(criteria.usageArea)) return false
    if (criteria.minWeight && product.weight < criteria.minWeight) return false
    if (criteria.maxWeight && product.weight > criteria.maxWeight) return false
    if (criteria.minWidth && product.width < criteria.minWidth) return false
    if (criteria.maxWidth && product.width > criteria.maxWidth) return false
    if (criteria.priceCategory && product.priceCategory !== criteria.priceCategory) return false
    if (criteria.fireRetardant && !product.fireRetardant) return false
    if (criteria.search) {
      const searchLower = criteria.search.toLowerCase()
      const matchesName = product.name.toLowerCase().includes(searchLower)
      const matchesSku = product.sku.toLowerCase().includes(searchLower)
      const matchesPattern = product.pattern?.toLowerCase().includes(searchLower)
      if (!matchesName && !matchesSku && !matchesPattern) return false
    }
    return true
  })
}
